
services:
  web:
    build:
      context: .
      dockerfile: Flask-Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redishost

  redishost:
    image: redis:latest
    ports:
      - "6379:6379" 


